package model;

public enum Generos {
	ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR, MUSIC, MYSTERY, ROMANCE, SCIENCEFICTION, THRILLER, TVMOVIE, WAR, WESTERN 
}
